version: 0.2
    
phases:
  install:
    runtime-versions:
      dotnet: 6.0
   
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore AddressBook.sln
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet build AddressBook.sln
      - echo Test started on `date`
      - dotnet test AddressBook.sln
      
artifacts:
  files:
    - ./**/*