version: 0.2
    
phases:
  install:
    runtime-versions:
      dotnet: 6.0
   
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore AddressBook.sln
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet build AddressBook.sln
      - echo Test started on `date`
      - dotnet test AddressBook.sln

  post_build:
    commands:
      - echo Publish started on `date`
      # https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/dotnet-linux-platform-bundle-app.html
      - dotnet publish -c Release AddressBook.API/AddressBook.API.csproj
      - echo $CODEBUILD_SRC_DIR
      
artifacts:
  files:
    - '**/*'
  name: addressbook.api/builds/$CODEBUILD_BUILD_NUMBER
  base-directory: AddressBook.API/bin/Release/net6.0/publish